overrides:
  "@iconify/tools": "5.0.12"

minimumReleaseAge: 43200

allowBuilds:
  '@sentry/cli': true
  esbuild: true
  puppeteer: true
  sharp: true
minimumReleaseAgeExclude:
  # Renovate security update: @xmldom/xmldom@0.9.12
  - "@xmldom/xmldom@0.9.12"
  # Renovate security update: maplibre-gl@6.4.1
  - maplibre-gl@6.4.1
  # Renovate security update: sharp@0.35.4
  - sharp@0.35.4
